### PR TITLE
Update to Zwift 1.0.50775

### PR DESCRIPTION
**Pull request by oldnapalm**
Had an issue with SerializeToString when there was no "power" field and it's defined as "required" in protobuf. Happened because I use virtual power (estimated from speed sensor) and looks like in this case when power is zero the field is missing. Should all fields be optional (except id and world_time which we know will always be set)?

### CODE REVIEW

**Comment by zoffline** [comment]
Holding off on this for a day or two since Zwift often likes to push minor updates shortly after their monthly update. Feel free to commit updates like this yourself if you're willing to do a Win release as well (and no proto files need generating).

**Comment by oldnapalm** [comment]
You are right, better wait a few days for minor updates, last month they released 3 in a couple days.

Sure, I will commit "clean" updates like this myself, just asked your review in this one because of the proto file changes.

Let me ask something regarding the Win release, which version of UPX are you using? With 3.96 if I leave `upx=True` I get this error when running the exe
`VCRUNTIME140.dll is either not designed to run on windows or it contains an error. ... Error status 0xc000000d.`

Also, do you use PyWin32 or pypiwin32?

**Comment by oldnapalm** [comment]
> Should all fields be optional (except id and world_time which we know will always be set)?

Actually only roadTime is required.

id and worldTime we set before sending to client.

**Comment by oldnapalm** [comment]
> With 3.96 if I leave `upx=True` I get this error when running the exe
> `VCRUNTIME140.dll is either not designed to run on windows or it contains an error. ... Error status 0xc000000d.`

Was using Python 3, needed `upx_exclude='vcruntime140.dll'` in standalone.spec to avoid the error.

Using Python 2 it seems to work fine.

**Comment by zoffline** [comment]
> Also, do you use PyWin32 or pypiwin32?

Neither. I just use the stock install of python 3.8 from python.org. I'm not sure what UPX version I use; I don't recall ever explicitly installing it. I only did 'pip install pyinstaller' after installing python 3.8.

**Comment by oldnapalm** [comment]
> I only did 'pip install pyinstaller' after installing python 3.8.

I did the same.

I read this

> PyInstaller requires two Python modules in a Windows system. It requires either the PyWin32 or pypiwin32 Python extension for Windows. If you install PyInstaller using pip, and PyWin32 is not already installed, pypiwin32 is automatically installed. PyInstaller also requires the pefile package.

and thought you might have PyWin32 previously installed.

No idea why I have this error. Need to add `upx_exclude='vcruntime140.dll'` or use Python 2 to build the Win release.

**Pull request merged**
