### PR TITLE
Various commits

### PR DESCRIPTION
**Pull request by oldnapalm**
* Fix issues with Mac launcher 1.0.23 (issue #27)
* Update instructions to configure Mac client
* Fix issues with Windows launcher 1.0.50
* Add support for multiple profiles (tested with Windows and Mac, untested with Docker)
* Remove free trial limit from profile (mentioned in issue #25)
* Add Garmin Connect activity upload
* Fix multi profile on Android (issue #44)
* Update to Zwift 1.0.48969

### CODE REVIEW

**Comment by oldnapalm** [comment]
`/launcher/realms/zwift/protocol/openid-connect/auth` is also called by Windows client if you have launcher version 1.0.50

launcher.zwift.com is also used, so I think it should be added to hosts file in Windows too, or internet connection will be needed just to open the launcher.

**Comment by oldnapalm** [comment]
Added Mac OS X in simplest install instructions

Release in https://github.com/oldnapalm/zwift-offline/releases

**Comment by zoffline** [comment]
Awesome work! Thanks!

**Comment by zoffline** [comment]
Bah, didn't merge yet...

**Pull request merged**
