### PR TITLE
fix: More helpful explanation for multiplayer mode.

### PR DESCRIPTION
**Pull request by RobTS**
Thanks for creating and maintaining this project! I went through the setup yesterday (with an Android device) and spent a lot of time trying to get multiplayer registration to work until I finally saw that some html-based endpoints exist. These are used by the web version, but the mobile versions offer their own native forms and then do a POST to `/api/users` to register a user, which is not implemented in zwift-offline yet.

So I figured I would add a remark to the readme to improve the situation for newcomers.

EDIT: Just found the last bullet in the Android (non-rooted) instruction would have saved me a ton of time, as I did not realize `secure.zwift.com` is effectively the server's address (obviously it is in the hosts redirect, just a lack of association on my part), so I changed it to the android (rooted) version there.

### CODE REVIEW

**Comment by zoffline** [comment]
Thanks for the edits. Does modifying the address to use the zoffline IP instead of secure.zwift.com result in a certificate security warning though?

**Comment by oldnapalm** [comment]
> Does modifying the address to use the zoffline IP instead of secure.zwift.com result in a certificate security warning though?

Didn't test in rooted device, but since instructions don't mention importing CA certificate in system, I guess it's the same as in non-rooted, security warning will be presented no matter if you use the IP or the hostname.

**Comment by RobTS** [comment]
@oldnapalm is correct in this. Also, I would have attempted to open the website on the computer, which would not have helped, either, as it had not been set up on that machine.

**Comment by zoffline** [comment]
Forgot about this pull request. Merging now. Thanks!

**Pull request merged**
