### PR TITLE
Add batch script to configure Windows 10 client

### PR DESCRIPTION
**Pull request by oldnapalm**
Not sure if you want to merge this, so opening pull request even being a minimal change.

I created a release (not in zoffline repo) with pyinstaller exes of get_profile and strava_auth. In strava_auth I used client-id and client-secret created by me, not sure if this can be a problem. If you want I can add the release in zoffline or remove it if it's an issue with Strava.

https://github.com/oldnapalm/zoffline-helper/releases/tag/zoffline_helper

### CODE REVIEW

**Comment by zoffline** [comment]
Very nice! Feel free to incorporate zoffline-helper in this repository or if you prefer, the README can be updated to state your zoffline-helper is the easiest way to install on Windows.

**Comment by oldnapalm** [comment]
I would incorporate it in this repository, but I'm now sure how to do it. Add one zip with all exes or a separate package for the scripts?

I have an issue with strata_auth: if I build the exe with Python 3, this redirection doesn't work https://github.com/zoffline/zwift-offline/blob/ada795ec62df84db0f1dbb5c51e478422479a101/scripts/strava_auth.py#L88

Also, Windows Defender detects it and get_profile as malware. I know there's a note about this in the release, but it doesn't happen with zoffline.

Do you want me to add the spec files and changes to the scripts in this repository?

**Comment by zoffline** [comment]
"I have an issue with strata_auth: if I build the exe with Python 3, this redirection doesn't work"
Weird. It works with 2 though?

I'd probably just create a single release with all the zoffline-helper scripts and link to it in the README.

"Do you want me to add the spec files and changes to the scripts in this repository?"
Go for it

**Comment by oldnapalm** [comment]
> Weird. It works with 2 though?

Yes, with 2 it works.

Do you want to take a look or can I release as it is?

**Comment by zoffline** [comment]
Can release as is. If you've got to build it with 2, so be it.

**Pull request merged**
