### PR TITLE
Pro names

### PR DESCRIPTION
**Pull request by daktak**
Add a script to pull top 100 riders female and male from procyclingstats and use this for the bot naming.

### CODE REVIEW

**Comment by daktak** [comment]
I suspect the country codes in your bot.txt are not phone number codes as I had hoped. do you have a way to map ?

**Comment by oldnapalm** [comment]
> I suspect the country codes in your bot.txt are not phone number codes as I had hoped. do you have a way to map ?

They are ISO 3166-1 numeric codes, you can use https://pypi.org/project/iso3166/

**Comment by daktak** [comment]
updated

**Comment by oldnapalm** [comment]
I think the file pro_riders.json should be either optional (used if exists in storage folder, otherwise keep current random names) or replace bot.txt (notice that it's included in the pyinstaller bundle).

**Comment by oldnapalm** [comment]
I think it's not necessary, it's not a big deal having duplicated names, it happens with random first and last names too (there are 100 last names and only the initial of first name is displayed in nearby list anyway).

Can you run the updated getter script and update bot.txt please?

**Comment by daktak** [comment]
Updated to allow for uneven male/female ratios if we source names from elsewhere. I'd like to write a script to source from a given Strava club for example.

**Comment by oldnapalm** [comment]
Made a little change to use boolean instead of string and eval. Can you re-run the script and update bot.txt please?

**Comment by jricoclq** [comment]
[bot.txt](https://github.com/zoffline/zwift-offline/files/11662719/bot.txt)

**Comment by jricoclq** [comment]
Can we indicate the team that the cyclist belongs to, as well as the Cycling Jerseys he is wearing?

**Comment by oldnapalm** [comment]
You can get the jerseys hashes (signatures) from the file cdn/gameassets/GameDictionary.xml

**Comment by daktak** [comment]
> I grabbed the names of 3853 professional cyclists from the PCS ranking, so that duplicate names would not appear on the list. [bot.txt](https://github.com/zoffline/zwift-offline/files/11662721/bot.txt)

You can pass the number of pages to grab in the get_pro_names.py (-p 12) for ~ 2400 names men and women, or -m -p 25 for ~ 2500 men.

**Comment by daktak** [comment]
> Can we indicate the team that the cyclist belongs to, as well as the Cycling Jerseys he is wearing?

https://github.com/zoffline/zwift-offline/pull/248 - added flags for this
-j -e -t 
to get jerseys, equipment (bike, wheels, helmet,), -t for team abbreviation

**Pull request merged**
