### PR TITLE
WIP: Option to overide a players equipment - player_profile.txt

### PR DESCRIPTION
**Pull request by daktak**
Same format as ghost_profile.txt

### CODE REVIEW

**Comment by daktak** [comment]
This would allow a user to set jerseys that are not normally available for use, and not mess up profile.bin from zwift.

**Comment by fatsbrown** [comment]
I don't think this will work, the equipment would be visible only to other players, not to yourself. Moreover, you must have the equipment in your garage, otherwise it won't be visible even if you assign directly in player profile.

See #328 for details.

**Comment by daktak** [comment]
Yeah I imagine profile.bin is the source of data for the client

**Comment by fatsbrown** [comment]
Yes, you could make changes after this https://github.com/zoffline/zwift-offline/blob/235d090bf1a99a31e37061493d2248f6e54cf7fa/zwift_offline.py#L1754 but since the items must be owned it doesn't make sense, the user can simply select them in the garage instead.

**Pull request closed without merging**
